version: '3.8'

services:
  xrdp:
    build: .
    container_name: xrdp
    privileged: true
    ports:
      - "3389:3389"
    restart: unless-stopped
    environment:
      - DISPLAY=:10
      - XDG_RUNTIME_DIR=/run/user/1000
      - PULSE_RUNTIME_PATH=/run/pulse
      - HOME=/home/xrdpuser
      - USER=xrdpuser
      - XAUTHORITY=/home/xrdpuser/.Xauthority
      - LANG=en_US.UTF-8
      - LC_ALL=en_US.UTF-8
    volumes:
      - xrdp-data:/var/lib/xrdp
      - xrdp-logs:/var/log
    cap_add:
      - ALL
    security_opt:
      - apparmor:unconfined
      - seccomp=unconfined

volumes:
  xrdp-data:
    driver: local
  xrdp-logs:
    driver: local
